### ISSUE TITLE
Error downloading polygon.public.dappnode.eth release from IPFS: Invalid manifest

### ISSUE THREAD

**Issue by KODYAcoder** [MysticRyuujin/dappnode-polygon#13]
URL: http://my.dappnode/installer/public/polygon.public.dappnode.eth

I get this error
Error: Error downloading polygon.public.dappnode.eth release from IPFS: Invalid manifest: 
  - manifest#.properties.globalEnvs.type must be array
    at f (file:///usr/src/app/node_modules/@dappnode/schemas/dist/index.js:8:100392)
    at downloadReleaseIpfsFn (file:///usr/src/app/packages/dappmanager/src/modules/release/ipfs/downloadRelease.ts:77:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Error downloading polygon.public.dappnode.eth release from IPFS: Invalid manifest: 
  - manifest#.properties.globalEnvs.type must be array
    at http://my.dappnode/static/js/main.57499c6d.js:2:586514
    at f (http://my.dappnode/static/js/main.57499c6d.js:2:544992)
    at Generator.<anonymous> (http://my.dappnode/static/js/main.57499c6d.js:2:546335)
    at Generator.next (http://my.dappnode/static/js/main.57499c6d.js:2:545355)
    at n (http://my.dappnode/static/js/main.57499c6d.js:2:540037)
    at s (http://my.dappnode/static/js/main.57499c6d.js:2:540240)
    at http://my.dappnode/static/js/main.57499c6d.js:2:540299
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/main.57499c6d.js:2:540180
    at b (http://my.dappnode/static/js/main.57499c6d.js:2:586320)

**Comment by MysticRyuujin** [comment]
Yeah, this repo hasn't been updated in well over a year and you're the first person to notice 😂

**Comment by KODYAcoder** [comment]
xdd, can u update it pls?

**Comment by MysticRyuujin** [comment]
Hmmm updating this would require a ton of changes, especially around the snapshot download. I'm not currently planning on updating it. But if someone wanted to work on it and create a PR I'd be happy to review and publish.
